### ISSUE TITLE
Building with different py2 and py3 requirements

### ISSUE THREAD

**Issue by psychemedia** [binder-examples/python2_runtime#1]
If I specify a python 2.7 environment in the `runtime.txt` file, is that the environment that packages specified in the `requirements.txt` file are installed into?

If I want to have py2 and py3 environments with different packages installed (eg becuase one package only works in py2, or py3), what's the best way to do that? Specify the py2 runtime (which seems to enable pip2.7?) and then install python packages using `pip3` and `pip2.7` in the `postbuild` file?

**Comment by choldgraf** [comment]
hmmm, that's a tricky one...are you hoping to let users switch fluidly between those two runtimes? I'd say the community is still figuring out the right way to hit these atypical workflows, so if you figure out a solution that works for you, please do share it!

**Comment by willingc** [comment]
@psychemedia One way you can accomplish this (though not ideal) would be to create a python2 branch and a python3 branch and then create a binder button for each branch.

**Comment by yuvipanda** [comment]
If you specify python-2.7 in the runtime.txt, then:

1. A python3 environment is created & installed (this is what the notebook runs from)
2. A python2 environment is created and registered
3. Contents of 'requirements.txt' are installed into the python2 environment
4. Contents of a new file, 'requirements3.txt' are installed into the python3 environment.

This is already implemented and should let you do what you need.

**Comment by choldgraf** [comment]
Updated the README with this language:

https://github.com/binder-examples/python2_runtime/blob/master/README.md

Gonna close this now, but @psychemedia feel free to re-open if there are still questions!
